### ISSUE TITLE
timestampで小数点以下の秒が０パディングされていない

### ISSUE THREAD

**Issue by andoh104** [ito-san/rosbag2_csv#2]
timestampで小数点以下の秒が０パディングされていないため、正しくソートされない問題が発生

```
2022/07/14 12:54:00.990263110　←小数点以下9桁が正しい
2022/07/14 12:54:01.1469722　　←0パディングされないため桁を間違う
2022/07/14 12:54:01.001469722　←これが正しい形
```

以下で修正できそう。
`  date = '\'{}.{:0>9}'.format(time.strftime('%Y/%m/%d %H:%M:%S', time.localtime(ts / 1000 / 1000 / 1000)), ts % (1000 * 1000 * 1000))
`
→効果確認済み

**Comment by ito-san** [comment]
@andoh104 是非PRをお願いいたします! :bow:

**Comment by andoh104** [comment]
しばらくお待ち下さい（空いた時にやります）

**Comment by ito-san** [comment]
ご対応ありがとうございました。
